name: wusel-landing Docker CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci:
    name: Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . -t wusel-landing
    - name: add tags
      run: |
          docker tag wusel-landing ${{ secrets.DOCKER_USER }}/wusel-landing:${{ github.sha }}
          docker tag wusel-landing ${{ secrets.DOCKER_USER }}/wusel-landing:latest
    - name: push to docker
      run: |
          docker push ${{ secrets.DOCKER_USER }}/wusel-landing:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/wusel-landing:latest

#  cd:
#      name: Deploy
#      runs-on: ubuntu-latest
#      needs: ci
#
#      steps:
#      - uses: actions/checkout@v2
#      - name: run wusel-landing image
#        uses: fifsky/ssh-action@master
#        with:
#          command: |
#            sudo docker stop $(sudo docker ps -a -q)
#            sudo docker container prune -y
#            sudo docker pull ${{ secrets.DOCKER_USER }}/wusel-landing:latest
#            sudo docker run -d -p 80:5000 wuselstani/wusel-landing
#          host: ${{ secrets.REMOTE_HOST }}
#          user: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.WUSEL_SERCRET }}
#          pass: ${{ secrets.REMOTE_PASSWORD}}
#