name: wusel-landing Docker CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  cd:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . -t wusel-landing
    - name: Tags
      run: |
          docker tag wusel-landing ${{ secrets.DOCKER_USER }}/wusel-landing:${{ github.sha }}
          docker tag wusel-landing ${{ secrets.DOCKER_USER }}/wusel-landing:latest
    - name: Push
      run: |
          docker push ${{ secrets.DOCKER_USER }}/wusel-landing:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/wusel-landing:latest
    - name: deploy to virtual privat server
      id: funny-deploy
      uses: BoatNg/funny-deploy@master
      env:
          REMOTE_HOST: "${{ secrets.REMOTE_HOST }}"
          REMOTE_USER: "${{ secrets.REMOTE_USER }}"
          REMOTE_PASSWORD: "${{ secrets.REMOTE_PASSWORD }}"
          REMOTE_PATH: "/home/runner/work/wusel-landing/wusel-landing/dist"
          SOURCE: "dist/"

